### ISSUE TITLE
Race Condition Problems

### ISSUE THREAD

**Issue by scoopex** [demestav/django-admin-edit-lock#1]
It seems that this library does to protect the handled models with a reliable behavior.

Our environment:
```
$ grep django  requirements.txt 
django==3.1.1
django-admin==2.0.1
django-extensions==3.0.8
django-colorfield==0.3.2
django-admin-thumbnails==0.2.5
django-material-admin==1.7.8
django-private-storage==2.2.2
django-storages==1.9.1
django-rq==2.3.2
django-auth-adfs==1.7.0
django-admin-edit-lock==0.3.0
django-stubs==1.8.0
```

Envrionment:
- Single Worker Pod
- PostgreSQL Database

Settings:
```
ADMIN_EDIT_LOCK_DURATION = 15
ADMIN_EDIT_LOCK_MAX_DURATION = 900
```

The model class:
```
class BaseAdmin(AdminEditLockMixin, admin.ModelAdmin):
....
    @property
    def id(self):
        # the django-admin-edit-lock depends on models having an id attribute
        return self.name
....
```

Our problem:
1. Open two idendepended browser windows with two different users
2. Open the edit view of the model in both windows with a delay of ~1 second -> both windows show the edit view 
3. Make a change in the second window an press save -> Change can be performed 
4. Make a change in the first window an press save -> Change can be performed 

This happens not always, but in 50% of the cases.

Did we miss something important or is this really a bug?

**Comment by demestav** [comment]
Thanks for taking the time to describe this clearly and in detail.

Indeed it seems like a race condition problem. Did the problem ever occurred in longer delays between the two requests (step 2 from your list)?

**Comment by scoopex** [comment]
I am not really sure, but i think so.
If you like, i can evaluate your changes in my environment.

**Comment by demestav** [comment]
> I am not really sure, but i think so.

Apart from the race condition, maybe something else is going on if this happens in longer duration scenarios. Maybe I am wrong, but I am thinking that if there are multiple workers (Gunicorn et al) and the cache backend is memory based, each worker would have an isolated cache, leading to the problem you describe.

EDIT: Based on Django documentation (https://docs.djangoproject.com/en/3.2/topics/cache/#local-memory-caching):

> Note that each process will have its own private cache instance, which means no cross-process caching is possible.

I was able to reproduce this, using the setup I described above.

**Comment by scoopex** [comment]
Thanks for the feedback. I added the following configuration to my project configuration:

settings.py
```
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{env.redis_host()}:{env.redis_port()}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "tenant-control-cache"
    }
}
```

I added "django_redis" to my project requirements. It seems that the lock managment now works for multiple instances of the worker. I think it would bee a good idea to add some documentation to the project to prevent problems like my problem.

**Comment by demestav** [comment]
Thanks for reporting back. I am glad we got it resolved!

>  I think it would bee a good idea to add some documentation to the project to prevent problems like my problem.

I have added it at the top of the README.md for now.
