### ISSUE TITLE
Display the name of the locking user

### ISSUE THREAD

**Issue by scoopex** [demestav/django-admin-edit-lock#2]
If the edit of a object is prevented by the locking mechanism (view object), it would be great to get a information which user is currently editing the object.

Secondly, the view duration of `notify_user()` is relatively short  - a longer viewtime (i.e. 5 seconds) would be great.

**Comment by demestav** [comment]
> ... it would be great to get a information which user is currently editing the object.

I can understand the usefulness of this, but I am thinking that maybe there are cases when sharing the details of the person editing the entry, is not desirable. If both cases are valid, maybe a configuration parameter can be added.

> Secondly, the view duration of `notify_user()` is relatively short - a longer viewtime (i.e. 5 seconds) would be great.

Not sure what you mean here. The standard django message framework is used for notifications. There is no custom code to render them; to the best of my knowledge the django admin displays them statically on the top of the screen. Are you using a custom admin theme or something similar?

**Comment by scoopex** [comment]
Regarding the message display: 
The display of the lock information is only displayed for a short period of time. After that, the message disappears.
If there is not possibility to raise the display time only for these certain types of messages, i will try to raise the  display time globally.

**Comment by demestav** [comment]
Are you using a custom admin theme? The default way that django admin displays the messages is static, it does not disappear. 

See relevant screenshot:
![image](https://user-images.githubusercontent.com/1180929/133593479-397e8c5e-b90a-48e1-a969-654e37169ee2.png)

**Comment by demestav** [comment]
>If the edit of a object is prevented by the locking mechanism (view object), it would be great to get a information which user is currently editing the object.

@scoopex I have added the requested feature in the branch https://github.com/demestav/django-admin-edit-lock/tree/feature/display-owner

**Comment by scoopex** [comment]
Thanks cool, can you publish that as a release? :-)

**Comment by demestav** [comment]
@scoopex I have just published this in 0.4.0.

I will now close this since the feature request is complete. As explained above, the other issue you are having seems unrelated to the package, and therefore this issue. Having said that, I would be happy to help you out, if I can. Just reply here.
